sonar.projectKey=agentman3334-key
sonar.organization=agentman3334
sonar.sources=backend/app,index.html
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.cpd.exclusions=frontend/src/data/**